
server:
  port: 7777

spring:
  jackson:
    default_property_inclusion: non_default
    date_format: yyyy-MM-dd'T'HH:mm:ss
    joda_date_time_format: yyyy-MM-dd'T'HH:mm:ss
    property_naming_strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  data:
    mongodb:
      uri: mongodb://localhost:27017/duic
#  main:
#    web_application_type: reactive
#  resources:
#    static_locations:
#      - "classpath:/META-INF/public-web-resources"

duic:
  root_email: kevinz@weghst.com
  root_password: 123456
  jwt:
    secret: U2FsdGVkX1/jO0KlWumac4yDM8rOgWPkaV0KrSHDynWOP6n8FMJB9uSc8EW/qM+VagrMBAXGpyw=
    expires_in: 180
